### ISSUE TITLE
Use 'extras' for optional dependencies

### ISSUE THREAD

**Issue by ahal** [mozilla/adr#58]
When installing `adr` we pull in a lot of dependencies. A lot of these are for "optional" features, like various caching backends or the web app. We should set up the `pyproject.toml` with the  [extras](https://python-poetry.org/docs/pyproject/#extras) feature.

**Comment by marco-c** [comment]
@ahal was this done with https://github.com/mozilla/adr/commit/a9de1da216b858b5b1b48a410aad552fd77e4ac7?

**Comment by ahal** [comment]
Yes, thanks for the reminder.
