### ISSUE TITLE
Renew items in the cache when they are accessed again

### ISSUE THREAD

**Issue by marco-c** [mozilla/adr#79]
Currently, an access to the cache doesn't renew its expiration. For our use cases, I think it makes more sense to renew it.

**Comment by ahal** [comment]
We can create a custom cache store that does this like this:
https://github.com/mozilla/adr/blob/master/adr/util/cache_stores.py

Upstream class is here:
https://github.com/sdispater/cachy/blob/master/cachy/stores/file_store.py
